[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn src.ultra_minimal:app --host 0.0.0.0 --port $PORT" 