[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

# Explicitly disable Nixpacks
[build.nixpacks]
enabled = false

# Force Dockerfile usage
[build.dockerfile]
enabled = true

[deploy]
healthcheckPath = "/health"
port = 8080
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 