[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
port = 8080
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Specify the backend directory as the root for deployment
[build.context]
path = "backend" 