[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
port = 8000
startCommand = "python test_simple.py"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 