[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
port = 8000
startCommand = "echo '=== RAILWAY.TOML STARTING ===' && echo 'Starting uvicorn...' && uvicorn src.ultra_minimal:app --host 0.0.0.0 --port $PORT"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[vars]
NIXPACKS_NO_CACHE = "1" 