[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
port = 8080
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Explicitly disable Nixpacks
[build.nixpacks]
enabled = false

# Specify that this is the root directory for deployment
[build.context]
path = "." 