[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
port = 8080
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python -m uvicorn src.app:app --host 0.0.0.0 --port 8080" 