[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python -m uvicorn src.app:app --host 0.0.0.0 --port 8000 --workers 1"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 