[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
port = 8080
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python -m uvicorn src.app_progressive:app --host 0.0.0.0 --port 8080" 