[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
port = 3001
startCommand = "uvicorn src.simple_app:app --host 0.0.0.0"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[vars]
NIXPACKS_NO_CACHE = "1" 