[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
port = 8080
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Specify that this is the root directory for deployment
[build.context]
path = "." 